"""Add subgoal relationship

Revision ID: 998642584338
Revises: bf02fc20df4f
Create Date: 2019-05-27 15:23:51.858562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998642584338'
down_revision = 'bf02fc20df4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('main_goal_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'goal', 'goal', ['main_goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goal', type_='foreignkey')
    op.drop_column('goal', 'main_goal_id')
    # ### end Alembic commands ###
