"""Create Progression Table

Revision ID: bf02fc20df4f
Revises: 4038b8c01fe9
Create Date: 2019-05-15 10:52:08.479712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf02fc20df4f'
down_revision = '4038b8c01fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_progression',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discarded', sa.Boolean(), nullable=True),
    sa.Column('goal_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_progression')
    # ### end Alembic commands ###
